### ISSUE TITLE
error: failed to run custom build command for `rquickjs-sys v0.1.7`

### ISSUE THREAD

**Issue by janpauldahlke** [DelSkayn/rquickjs#96]
Hello and thanks for your afford.

Consider my small Cargo.toml 
```toml
[package]
name = "rust_surreal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rquickjs-sys = "0.1.7"
surrealdb = "1.0.0-beta.8"
tokio = { version = "1", features = ["full"]}
anyhow = "1"
```

that and the out on `cargo build`

```
[foobar@fuckup rust_surreal]$ cargo build
   Compiling ctor v0.1.26
   Compiling serde_derive v1.0.147
   Compiling thiserror-impl v1.0.37
   Compiling pin-project-internal v1.0.12
   Compiling time-macros-impl v0.1.2
   Compiling wasm-bindgen-backend v0.2.83
   Compiling tracing-attributes v0.1.23
   Compiling darling_core v0.14.2
   Compiling futures-macro v0.3.25
   Compiling tokio-macros v1.8.0
   Compiling async-trait v0.1.58
   Compiling surrealdb-derive v0.4.0
   Compiling async-recursion v1.0.0
   Compiling proc-macro-error v1.0.4
   Compiling openssl-sys v0.9.77
   Compiling rquickjs-sys v0.1.7
error: failed to run custom build command for `rquickjs-sys v0.1.7`

Caused by:
  process didn't exit successfully: `/home/foobardev/rust_surreal/target/debug/build/rquickjs-sys-9e9eb92022a1541c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CARGO_FEATURE_EXPORTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_BINDGEN
  cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATE_BINDINGS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_BYTECODE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_LEAKS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MEM
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_OBJECTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_ATOMS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_SHAPES
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MODULE_RESOLVE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_PROMISE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_READ_OBJECT

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/janpaul/.cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.1.7/build.rs:136:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Could you give me a hint, how to achieve my build here? Tanks in advance.

Kind regards.
